# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Shimmering Flats
tagline:          ''
description:      'Personal Blog of <a href="http://weibo.com/flickerlight" target="_blank">@flickerlight</a>.'
url:              http://flickerlight.github.io
baseurl:          /

author:
  name:           'Flickerlight'
  url:            http://weibo.com/flickerlight

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate]


category_list:
  Motherhood: '/motherhood'
  Healthcare: '/healthcare'
  Other: '/other'