# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:              Caramel's Pride
tagline:            
paginate:            1
baseurl: "" #if use for personal site. The subpath of your site, e.g. /blog/
url: "https://flickerlight.github.io" # the base hostname & protocol for your site

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lynn Chen
  url:               
  email:             cwlme82@gmail.com


pages_list:       
  About: '/about'
  Archive: '/archive'
  #Feed: '/atom.xml'

category_list:
  Mothercare: '/mothercare'
  Other: '/other'
  
